SET check_function_bodies = false;
INSERT INTO public.menu (id, image, weight, title, ingredients, price) VALUES ('1', 'manhattan.jpeg', 555, 'Manhattan Pizza', '(double portion of mushrooms), Mushrooms, Mozzarella, Pepperoni, Alfredo sauce', 12);
INSERT INTO public.menu (id, image, weight, title, ingredients, price) VALUES ('2', 'pepperoni-w-tomatoes.jpeg', 554, 'Pepperoni and Tomato Pizza', 'Mozzarella, pepperoni, tomatoes, barbecue sauce', 12);
INSERT INTO public.menu (id, image, weight, title, ingredients, price) VALUES ('3', 'ham-w-mushrooms.jpeg', 545, 'Pizza with ham', 'Ham, Mushrooms, Mozzarella, PizzaStack Sauce', 12);
INSERT INTO public.menu (id, image, weight, title, ingredients, price) VALUES ('4', 'texas.jpeg', 550, 'Texas Pizza', 'Corn, Onion, Mushrooms, Bavarian Sausages, Mozzarella, Barbecue Sauce', 12);
INSERT INTO public.menu (id, image, weight, title, ingredients, price) VALUES ('5', 'pepperoni.jpeg', 560, 'Pepperoni Pizza', 'Mozzarella, Pepperoni, PizzaStack Sauce', 13);
INSERT INTO public.menu (id, image, weight, title, ingredients, price) VALUES ('6', 'margarita.jpeg', 552, 'Margherita Pizza', '(double portion of mozzarella), Mozzarella, PizzaStack Sauce', 13);
INSERT INTO public.menu (id, image, weight, title, ingredients, price) VALUES ('7', 'barbecue.jpeg', 552, 'Barbecue Pizza', 'Chicken, Onion, Bacon, Mushrooms, Mozzarella, Barbecue Sauce', 13);
INSERT INTO public.menu (id, image, weight, title, ingredients, price) VALUES ('8', 'grill-mix.jpeg', 569, 'Grill Mix Pizza', 'Chicken, Meatballs, Onion, Bacon, Bell Pepper, Mozzarella, Barbecue Sauce', 13);
INSERT INTO public.menu (id, image, weight, title, ingredients, price) VALUES ('9', 'carbonara.jpeg', 540, 'Carbonara Pizza', 'Onion, Bacon, Ham, Mushrooms, Mozzarella, Alfredo Sauce', 13);
